name: HTML CI (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  html-validate:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install htmlhint locally (fast, no global perms needed)
      - name: Install htmlhint
        run: npm install htmlhint --save-dev

      # Validate all HTML files anywhere in the repo.
      # If none exist, skip with a friendly message.
      - name: Validate HTML files (if any)
        shell: pwsh
        run: |
          $files = Get-ChildItem -Path . -Recurse -Include *.html
          if ($files.Count -eq 0) {
            Write-Host "No HTML files found, skipping validation."
            exit 0
          }
          npx htmlhint "**/*.html"

