name: HTML & CSS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate HTML files
      uses: Cyb3r-Jak3/html5validator-action@v0.4.4
      with:
        root: .
    
    - name: Lint CSS files
      run: |
        npm install -g stylelint stylelint-config-standard
        npx stylelint "**/*.css"

